### ISSUE TITLE
`package.metadata.cargo-equip-bin.patch.mod-dependencies`

### ISSUE THREAD

**Issue by qryxip** [qryxip/cargo-equip#2]
#1 のような場合に`bin`側で`mod-dependencies`を設定できるようにする。

```toml
[package.metadata.cargo-equip-bin.patch.mod-dependencies]
other-persons-lib = { "foo" = ["bar", "baz] }
```
